server:
  servlet:
    context-path: /zdww
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://123.57.10.22:3306/takeaway?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: litchi
    password: (hyy520LITCHI)
  mvc:
    view:
      prefix: /templates/
      suffix: .html
 #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false
#mybatis配置
mybatis:
  type-aliases-package: com.zhongdianwanwei.service.model
  mapper-locations: classpath:mapper/*Mapper.xml
mybatis-plus:
  mapper-location: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhongdianwanwei.service.model
  check-config-location: false
  executor-type: simple
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    column-underline: true
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
